### ISSUE TITLE
Update docs on best practices for wrapping an external API

### ISSUE THREAD

**Issue by frankcarey** [strongloop/loopback-connector-rest#16]
I'm trying to wrap the forecast.io weather data API and having a hard time fully understanding the documentation at http://docs.strongloop.com/display/LB/REST+connector. There seem to be leaps/gaps where it's not clear where code should go or how I can understand why my models doesn't show up.

The API is just a simple GET request with a lat-long appended to the url. I assume the best way is to define something like simple like this..

I first created the setup via the REST Connector instructions above, and only after creating a simple model in /common/models/json was I able to see Weather model show up in the rest explorer, but all it creates in an "invoke" endpoint, that gave a 500 (and crashed the server) when I didn't specify the lat and long.

I then switched to trying the instructions at http://docs.strongloop.com/display/LB/REST+example+-+creating+the+back-end

Where it says:
"If you're not interested only in CRUD operations, but want to implement custom logic, skip the Yeoman steps and add custom logic for post-processing the data returned by the Sharepoint API call.  
Copy and paste the code below.
Save it to /server/boot/document.js.  That's where you put custom models and other code you want executed on app startup."

OK, so I put /server/boot/document.js there, but the model doesn't show up in the REST explorer. I know it's being run because the console.log() is outputting "Model" to the command line. Any ideas?

**Comment by richardpringle** [comment]
@crandmck, is this really a documentation issue? I know there are a couple things that I could clear up at http://docs.strongloop.com/display/LB/REST+connector but I actually can't find this guy: http://docs.strongloop.com/display/LB/REST+example+-+creating+the+back-end.

I feel like it would make way more sense to have the [geo example](https://github.com/strongloop/loopback-connector-rest/tree/master/example) that is used in the docs as its own repo instead of  [loopback-example-rest-connector](https://github.com/strongloop/loopback-example-rest-connector) as that example is too simple (there are no custom functions, it's simply performing a GET request with no arguments).

**Comment by richardpringle** [comment]
@frankcarey, thanks a lot for your feedback. I will try and fix up the wording a little bit and be more descriptive. If you have any specific phrases that you found ambiguous, feel free to comment on here directly.

I'm glad you were still able to accomplish something though!

**Comment by crandmck** [comment]
@richardpringle We recently "hid" https://docs.strongloop.com/display/LB/REST+example+-+creating+the+back-end along with  https://docs.strongloop.com/display/LB/REST+example+-+adding+a+client+app because we deprecated https://github.com/strongloop/loopback-example-APIClientApp.  It was an old example that wasn't being maintained.

However, those docs are still visible if you are logged in to Confluence using the StrongLoop account.

Since I don't think we want to resurrect that example app (you can take that up with @superkhau), perhaps you could just take some of the code examples and other useful information from those docs and put it into https://docs.strongloop.com/display/LB/REST+connector.  That's my recommendation; unless you feel strongly we need to keep the deprecated example.

**Comment by richardpringle** [comment]
@crandmck, I don't think we necessarily need to keep the deprecated example, I just don't think the current example covers enough of the _connector's_ functionality. You can do all these things like add custom functions and the example is only performing a `GET` request.

@superkhau, you have an opinion here? I'm thinking [lb-ex-rest-connector](https://github.com/strongloop/loopback-example-rest-connector) could use an update next sprint.

**Comment by superkhau** [comment]
@crandmck is correct about not maintaining the deprecated example. What we need to do, is look at the uses cases from the example dir and merge the useful things with https://github.com/strongloop/loopback-example-rest-connector

@crandmck Let's keep those old docs deprecated and @richardpringle can create an issue to remove the example dir from this project, update the code to LB2 standards, put the good stuff in https://github.com/strongloop/loopback-example-rest-connector and you can link/create docs based on the updated example.

@richardpringle Please put this issue on TOB (unless you're already working on it) and we'll get it prioritized for next sprint. I believe you may need a 3 point spike to figure out what we need to demonstrate, what we can keep, what to remove, etc. And probably another 5 or more to do the repo updates/coding. However, please assign your own estimates as it should be what you're comfortable with. ;) Ping me when you need more clarifications.
