### ISSUE TITLE
How to un-"share" the invoke method 

### ISSUE THREAD

**Issue by frankcarey** [strongloop/loopback-connector-rest#17]
invoke is injected with shared=true, but when I try to access it in common/models/mymodel.js it seems like it isn't there.

```Javascript
module.exports = function(myModel) {

  // This works.
  mymodel.newMethod() {
    myModel.invoke(...);
  }
  mymodel.newMethod.share = true;

  // This fails (invoke is undefined it says)
  mymodel.invoke.shared = false;

}
```

**Comment by jswift** [comment]
MyModel.disableRemoteMethod('invoke', true);

Will remove the invoke method from the api.

**Comment by richardpringle** [comment]
@frankcarey, I'm a little confused here. Is this issue in the right repo? It looks to me like the issue belongs in [strong-remoting](https://github.com/strongloop/strong-remoting) or [LoopBack](https://github.com/strongloop/loopback).

I also realize that this issue is really old. Please close it or let me know if I can if it is no longer relevant. Sorry about the initial lack of response.
