### ISSUE TITLE
Cannot generate new REST datasource with Strongloop

### ISSUE THREAD

**Issue by kenmorechalfant** [strongloop/loopback-connector-rest#52]
I'm new to Loopback, was following this page here: https://docs.strongloop.com/display/public/LB/REST+connector

```
$ npm install loopback-connector-rest --save
$ slc loopback:datasource
? Enter the data-source name: testrestDS
? Select the connector ...
> REST Services (supported by StrongLoop)
```

And then I get this error:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'facetName' of undefined
    at exports._extend (util.js:770:21)
    at module.exports.yeoman.generators.Base.extend.dataSource (/usr/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:169:18)
    at /usr/lib/node_modules/strongloop/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I've tried a couple other connector types in the generator and they work (like Mongo even though I don't have that connector installed).

Ubuntu 14.04 64-bit
node v5.7.1
npm v3.6.0
slc v6.0.0
loopback v2.27.0
loopback-connector-rest v1.10.2

**Comment by richardpringle** [comment]
@kenmorechalfant, So the rest connector isn't like the other connectors in the sense that you don't create a datasource to attach a model to. It is actually just a service to expose other REST APIs in your back-end logic.

It doesn't really make sense to have the code-generator scaffold a datasource with "rest" as its connector since you have to fill in all of the metadata anyway.

Does that make sense?

I am going to close this issue but please feel free to carry on the discussion in here. If the documentation can be clarified (which I'm guessing it can), we can open up specific issues for the doc fixes. Sound good?

Cheers
